#pragma once

#define SURFACES_NAME "Surfaces"
#define SURFACES_COLORED_LIGHTS_NAME "Surfaces (colored lights)"
#define SURFACES_RGBA_NAME "Surfaces (RGBA)"
#define SURFACES_RGBA_COLORED_LIGHTS_NAME "Surfaces (RGBA, colored lights)"
#define SURFACES_RGBA_NO_GLOW_NAME "Surfaces (RGBA, no glow texture)"
#define SURFACES_RGBA_NO_GLOW_COLORED_LIGHTS_NAME "Surfaces (RGBA, no glow texture, colored lights)"
#define SURFACES_ROTATED_NAME "Surfaces (rotated)"
#define SURFACES_ROTATED_COLORED_LIGHTS_NAME "Surfaces (rotated, colored lights)"
#define SURFACES_ROTATED_RGBA_NAME "Surfaces (rotated, RGBA)"
#define SURFACES_ROTATED_RGBA_COLORED_LIGHTS_NAME "Surfaces (rotated, RGBA, colored lights)"
#define SURFACES_ROTATED_RGBA_NO_GLOW_NAME "Surfaces (rotated, RGBA, no glow texture)"
#define SURFACES_ROTATED_RGBA_NO_GLOW_COLORED_LIGHTS_NAME "Surfaces (rotated, RGBA, no glow texture, colored lights)"
#define FENCES_NAME "Fences"
#define FENCES_COLORED_LIGHTS_NAME "Fences (colored lights)"
#define FENCES_RGBA_NAME "Fences (RGBA)"
#define FENCES_RGBA_COLORED_LIGHTS_NAME "Fences (RGBA, colored lights)"
#define FENCES_RGBA_NO_GLOW_NAME "Fences (RGBA, no glow texture)"
#define FENCES_RGBA_NO_GLOW_COLORED_LIGHTS_NAME "Fences (RGBA, no glow texture, colored lights)"
#define FENCES_ROTATED_NAME "Fences (rotated)"
#define FENCES_ROTATED_COLORED_LIGHTS_NAME "Fences (rotated, colored lights)"
#define FENCES_ROTATED_RGBA_NAME "Fences (rotated, RGBA)"
#define FENCES_ROTATED_RGBA_COLORED_LIGHTS_NAME "Fences (rotated, RGBA, colored lights)"
#define FENCES_ROTATED_RGBA_NO_GLOW_NAME "Fences (rotated, RGBA, no glow texture)"
#define FENCES_ROTATED_RGBA_NO_GLOW_COLORED_LIGHTS_NAME "Fences (rotated, RGBA, no glow texture, colored lights)"
#define TURBULENT_NAME "Turbulent"
#define TURBULENT_RGBA_NAME "Turbulent (RGBA)"
#define TURBULENT_LIT_NAME "Turbulent lit"
#define TURBULENT_COLORED_LIGHTS_NAME "Turbulent (colored lights)"
#define TURBULENT_RGBA_LIT_NAME "Turbulent lit (RGBA)"
#define TURBULENT_RGBA_COLORED_LIGHTS_NAME "Turbulent (RGBA, colored lights)"
#define TURBULENT_ROTATED_NAME "Turbulent (rotated)"
#define TURBULENT_ROTATED_RGBA_NAME "Turbulent (rotated, RGBA)"
#define TURBULENT_ROTATED_LIT_NAME "Turbulent lit (rotated)"
#define TURBULENT_ROTATED_COLORED_LIGHTS_NAME "Turbulent (rotated, colored lights)"
#define TURBULENT_ROTATED_RGBA_LIT_NAME "Turbulent lit (rotated, RGBA)"
#define TURBULENT_ROTATED_RGBA_COLORED_LIGHTS_NAME "Turbulent (rotated, RGBA, colored lights)"
#define SPRITES_NAME "Sprites"
#define ALIAS_NAME "Alias models"
#define ALIAS_ALPHA_NAME "Alias models (transparent)"
#define ALIAS_COLORED_LIGHTS_NAME "Alias models (colored lights)"
#define ALIAS_ALPHA_COLORED_LIGHTS_NAME "Alias models (transparent, colored lights)"
#define ALIAS_HOLEY_NAME "Alias models (holey)"
#define ALIAS_HOLEY_ALPHA_NAME "Alias models (holey, transparent)"
#define ALIAS_HOLEY_COLORED_LIGHTS_NAME "Alias models (holey, colored lights)"
#define ALIAS_HOLEY_ALPHA_COLORED_LIGHTS_NAME "Alias models (holey, transparent, colored lights)"
#define VIEWMODELS_NAME "Viewmodels"
#define VIEWMODELS_COLORED_LIGHTS_NAME "Viewmodels (colored lights)"
#define VIEWMODELS_HOLEY_NAME "Viewmodels (holey)"
#define VIEWMODELS_HOLEY_COLORED_LIGHTS_NAME "Viewmodels (holey, colored lights)"
#define PARTICLES_NAME "Particles"
#define COLORED_NAME "Colored"
#define CUTOUT_NAME "Cutout"
#define SKY_NAME "Sky"
#define SKY_RGBA_NAME "Sky (RGBA)"
#define TEXTURED_NAME "Textured"
