#pragma once

#define COLOR_FORMAT VK_FORMAT_R8G8B8A8_SRGB
#define DEPTH_FORMAT VK_FORMAT_D32_SFLOAT
#define SCREEN_TO_CONSOLE_MULTIPLIER 3
#define MAX_UNUSED_COUNT 16
#define MEMORY_BLOCK_SIZE 1024 * 1024
#define DESCRIPTOR_SET_COUNT 256
